// Site-wide configuration: languages, subjects, and UI strings.
// Concept files live in concepts/<lang>/<slug>.md and share the same slug across languages.

export const site = {
  name: "QuantRef",
  repo: "https://github.com/juliendealm/QuantRef",
  defaultLang: "fr",
  languages: ["fr", "en"],
};

// Order here is the order on the dashboard.
export const subjects = [
  { id: "probability", en: "Probability", fr: "Probabilités" },
  { id: "stochastic", en: "Stochastic Calculus", fr: "Calcul stochastique" },
  { id: "derivatives", en: "Derivatives Pricing", fr: "Pricing de dérivés" },
  { id: "risk", en: "Risk Management", fr: "Gestion du risque" },
  { id: "statistics", en: "Statistics & Econometrics", fr: "Statistiques & économétrie" },
  { id: "filtering", en: "Filtering & Time Series", fr: "Filtrage & séries temporelles" },
  { id: "portfolio", en: "Portfolio Theory", fr: "Théorie du portefeuille" },
  { id: "microstructure", en: "Market Microstructure", fr: "Microstructure de marché" },
];

// Section headings that the build recognises (for the revision card and interview bank).
export const sections = {
  en: { revision: "30-Second Revision", formulas: "Key Formulas", interview: "Interview Questions" },
  fr: { revision: "Révision en 30 secondes", formulas: "Formules clés", interview: "Questions d'entretien" },
};

export const ui = {
  en: {
    langName: "English",
    otherLang: "Français",
    dashboard: "Dashboard",
    concepts: "Concepts",
    graph: "Graph",
    review: "Review",
    interview: "Interview",
    search: "Search concepts… ( / )",
    noResults: "No results",
    tagline: "Personal reference notes for quantitative finance.",
    stats: { concepts: "concepts", formulas: "key formulas", questions: "interview questions", subjects: "subjects" },
    subjects: "Subjects",
    tags: "Tags",
    emptySubject: "No concepts yet.",
    difficulty: "Difficulty",
    interviewValue: "Interview value",
    prerequisites: "Prerequisites",
    learningPath: "Learning path",
    usedBy: "Used by",
    related: "Related",
    onThisPage: "On this page",
    subject: "Subject",
    edit: "Edit on GitHub",
    reviewedPrompt: "How well did you recall this?",
    again: "Again",
    hard: "Hard",
    good: "Good",
    easy: "Easy",
    nextReview: "Next review",
    reviewTitle: "Review",
    reviewIntro: "Cards are scheduled with spaced repetition and stored in this browser only.",
    due: "Due today",
    newCards: "New",
    later: "Scheduled later",
    nothingDue: "Nothing due. Come back tomorrow, or start a new card.",
    showAnswer: "Show card",
    openConcept: "Open concept",
    resetProgress: "Reset progress",
    graphTitle: "Prerequisite graph",
    graphIntro: "Arrows point from a prerequisite to the concept that builds on it. Drag to move around, scroll or use the buttons to zoom, click a node to open it, hover to highlight its lineage.",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoomFit: "Fit to screen",
    interviewTitle: "Interview bank",
    interviewIntro: "Every interview question from every concept, grouped by subject. Click a question to reveal hints and answers.",
    questions: "questions",
    all: "All",
    home: "Home",
    footer: "Built from Markdown with a small Node script. Formulas rendered with KaTeX at build time.",
    starLabel: "out of 5",
    level: ["Intro", "Core", "Solid", "Advanced", "Expert"],
    toggleTheme: "Toggle theme",
    langSwitch: "Lire en français",
    lastReviewed: "Last reviewed",
    never: "never",
    output: "Output",
    keyFormula: "Key formula",
    hint: "Hint",
    answer: "Answer",
    pitfall: "Pitfall",
  },
  fr: {
    langName: "Français",
    otherLang: "English",
    dashboard: "Accueil",
    concepts: "Concepts",
    graph: "Graphe",
    review: "Réviser",
    interview: "Entretien",
    search: "Chercher un concept… ( / )",
    noResults: "Aucun résultat",
    tagline: "Notes de référence personnelles en finance quantitative.",
    stats: { concepts: "concepts", formulas: "formules clés", questions: "questions d'entretien", subjects: "sujets" },
    subjects: "Sujets",
    tags: "Tags",
    emptySubject: "Aucun concept pour l'instant.",
    difficulty: "Difficulté",
    interviewValue: "Valeur en entretien",
    prerequisites: "Prérequis",
    learningPath: "Chemin d'apprentissage",
    usedBy: "Utilisé par",
    related: "Voir aussi",
    onThisPage: "Sur cette page",
    subject: "Sujet",
    edit: "Modifier sur GitHub",
    reviewedPrompt: "Tu t'en souvenais comment ?",
    again: "Oublié",
    hard: "Difficile",
    good: "Bien",
    easy: "Facile",
    nextReview: "Prochaine révision",
    reviewTitle: "Réviser",
    reviewIntro: "Les cartes sont planifiées par répétition espacée et stockées uniquement dans ce navigateur.",
    due: "À revoir aujourd'hui",
    newCards: "Nouvelles",
    later: "Planifiées plus tard",
    nothingDue: "Rien à revoir. Reviens demain, ou commence une nouvelle carte.",
    showAnswer: "Voir la carte",
    openConcept: "Ouvrir le concept",
    resetProgress: "Réinitialiser la progression",
    graphTitle: "Graphe des prérequis",
    graphIntro: "Les flèches vont d'un prérequis vers le concept qui s'appuie dessus. Fais glisser pour te déplacer, molette ou boutons pour zoomer, clique sur un nœud pour l'ouvrir, survole-le pour voir sa lignée.",
    zoomIn: "Zoomer",
    zoomOut: "Dézoomer",
    zoomFit: "Ajuster à l'écran",
    interviewTitle: "Banque d'entretien",
    interviewIntro: "Toutes les questions d'entretien de tous les concepts, groupées par sujet. Clique sur une question pour voir les indices et la réponse.",
    questions: "questions",
    all: "Tous",
    home: "Accueil",
    footer: "Généré depuis du Markdown par un petit script Node. Formules rendues avec KaTeX au build.",
    starLabel: "sur 5",
    level: ["Intro", "Base", "Solide", "Avancé", "Expert"],
    toggleTheme: "Changer de thème",
    langSwitch: "Read in English",
    lastReviewed: "Dernière révision",
    never: "jamais",
    output: "Sortie",
    keyFormula: "Formule clé",
    hint: "Indice",
    answer: "Réponse",
    pitfall: "Piège",
  },
};
